@preconcurrency import AppKit
import ApplicationServices
import CoreGraphics
import Foundation
import os
#if SWIFT_PACKAGE
import ScriberCore
#endif

enum PasteResult: Sendable {
    static let noEditableTargetMessage = "No editable text box was focused"

    case inserted
    case noEditableTarget(String)
    case failed(String)
}

/// Delivers a finished transcript to whatever text cursor is focused when
/// transcription completes.
///
/// Two rules shape this type:
///
/// 1. Starting a recording must stay instantaneous. Nothing on the record-start
///    path may send an Accessibility message, because those are synchronous
///    cross-process calls whose cost is set by the destination app, not by
///    Scriber. Target discovery therefore happens only at delivery time.
/// 2. Confirmation is allowed to be slow. Delivery is confirmed when the
///    destination requests the concealed in-flight pasteboard item, or when an
///    editable Accessibility target visibly mutates. Missing Accessibility
///    evidence is never treated as failure — see `docs/PASTE_ENGINE.md`.
@MainActor
final class PasteService {
    /// Accessibility messages block the caller. macOS defaults to a 6-second
    /// per-message timeout, and an unresponsive destination can spend all of it
    /// while Scriber's main actor waits. Delivery never depends on Accessibility
    /// succeeding, so every message is capped low enough to stay imperceptible.
    private static let accessibilityMessagingTimeout: Float = 0.2
    private static let maximumInspectedAncestors = 8
    private static let maximumInspectedMenuItems = 256
    /// A destination may request the promised transcript well after the Paste
    /// command lands. Waiting longer is strictly better than reporting a false
    /// failure, and this delay is only ever paid on the failing path.
    private static let pasteRequestTimeout = Duration.milliseconds(2_500)
    private static let clipboardRestoreDelay = Duration.milliseconds(500)
    private static let transientPasteboardTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]

    private(set) var targetScreen: NSScreen?

    /// Records only where the floating pill should appear. The frontmost window
    /// rectangle comes from the window server, so this performs no Accessibility
    /// traversal and adds no measurable latency to starting a recording.
    @discardableResult
    func captureTarget() -> NSScreen? {
        targetScreen = nil
        guard let runningApplication = NSWorkspace.shared.frontmostApplication else { return nil }
        targetScreen = Self.screenContainingFrontmostWindow(ownedBy: runningApplication.processIdentifier)
        return targetScreen
    }

    func clearTarget() {
        targetScreen = nil
    }

    func insert(_ text: String) async -> PasteResult {
        guard AXIsProcessTrusted() else { return .failed("Accessibility permission is not enabled.") }
        let target = currentFocusedPasteTarget()
        logDeliveryContext(chosen: target)
        guard let target else {
            logDeliveryOutcome("noEditableTarget-noTarget")
            return .noEditableTarget(PasteResult.noEditableTargetMessage)
        }
        let result = await pasteAtCurrentSelection(text, into: target)
        switch result {
        case .inserted: logDeliveryOutcome("inserted")
        case .noEditableTarget: logDeliveryOutcome("noEditableTarget")
        case .failed: logDeliveryOutcome("failed")
        }
        return result
    }

    // MARK: - Delivery diagnostics
    //
    // Privacy-safe diagnostics for target selection. Scriber picks its paste target
    // with `NSWorkspace.frontmostApplication`, but an LSUIElement app presenting a
    // nonactivating panel can hold keyboard focus without becoming frontmost.
    //
    // Record process identities and Accessibility roles only. Never log transcript
    // text: keeping in-flight dictation private is the whole point of the
    // concealed-pasteboard design, and a log would undo it.

    private static let diagnosticLog = Logger(
        subsystem: "com.gafiegarcia.scriber",
        category: "paste-target"
    )

    private func logDeliveryContext(chosen: FocusedTextTarget?) {
        let frontmost = NSWorkspace.shared.frontmostApplication?.processIdentifier
        let systemWide = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(systemWide, Self.accessibilityMessagingTimeout)

        var focusedApplicationPID: pid_t = 0
        if let focusedApplication = elementAttribute(systemWide, named: kAXFocusedApplicationAttribute) {
            AXUIElementGetPid(focusedApplication, &focusedApplicationPID)
        }

        var focusedElementPID: pid_t = 0
        var role = "-"
        var subrole = "-"
        if let focusedElement = elementAttribute(systemWide, named: kAXFocusedUIElementAttribute) {
            AXUIElementGetPid(focusedElement, &focusedElementPID)
            role = stringAttribute(focusedElement, named: kAXRoleAttribute) ?? "-"
            subrole = stringAttribute(focusedElement, named: kAXSubroleAttribute) ?? "-"
        }

        Self.diagnosticLog.info("""
        delivery frontmost=\(Self.identity(of: frontmost), privacy: .public) \
        focusedApp=\(Self.identity(of: focusedApplicationPID), privacy: .public) \
        focusedElement=\(Self.identity(of: focusedElementPID), privacy: .public) \
        role=\(role, privacy: .public) subrole=\(subrole, privacy: .public) \
        chosen=\(Self.identity(of: chosen?.pid), privacy: .public) \
        qualifiedTextFocus=\(chosen?.focusContainsTextInput ?? false, privacy: .public)
        """)
    }

    private func logDeliveryOutcome(_ outcome: String) {
        Self.diagnosticLog.info("delivery outcome=\(outcome, privacy: .public)")
    }

    private static func identity(of pid: pid_t?) -> String {
        guard let pid, pid != 0 else { return "none" }
        let application = NSRunningApplication(processIdentifier: pid)
        return "\(application?.bundleIdentifier ?? "unknown")(\(pid))"
    }

    // MARK: - Target discovery

    private func currentFocusedPasteTarget() -> FocusedTextTarget? {
        guard let pid = currentTargetPID() else { return nil }
        let application = AXUIElementCreateApplication(pid)
        AXUIElementSetMessagingTimeout(application, Self.accessibilityMessagingTimeout)

        // A destination may keep its real editor outside the Accessibility tree.
        // An empty inspection set is expected there, and process-level paste stays
        // safe because success is confirmed independently by the pasteboard probe.
        let inspected = focusedTextAncestry(in: application, pid: pid)
        // A focused secure field is the one case Scriber positively refuses:
        // dictation must never be pasted into a password box.
        guard !inspected.contains(where: isSecureTextElement) else { return nil }
        let observationElements = inspected.filter(isEditableTextElement)
        return FocusedTextTarget(
            application: application,
            pid: pid,
            observationElements: observationElements,
            focusContainsTextInput: !observationElements.isEmpty
        )
    }

    /// The process delivery should paste into.
    ///
    /// Normally the frontmost application, but keyboard focus wins when the two
    /// disagree. An accessory app presenting a nonactivating panel — Raycast's
    /// command bar, and Scriber's own pill — holds focus without ever becoming
    /// frontmost, and delivery must follow the caret the user can actually see.
    private func currentTargetPID() -> pid_t? {
        guard let frontmostPID = NSWorkspace.shared.frontmostApplication?.processIdentifier else { return nil }
        return keyboardFocusOwner(frontmostPID: frontmostPID) ?? frontmostPID
    }

    private func keyboardFocusOwner(frontmostPID: pid_t) -> pid_t? {
        let systemWide = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(systemWide, Self.accessibilityMessagingTimeout)
        guard let focused = elementAttribute(systemWide, named: kAXFocusedUIElementAttribute) else { return nil }
        var focusOwnerPID: pid_t = 0
        guard AXUIElementGetPid(focused, &focusOwnerPID) == .success else { return nil }
        guard KeyboardFocusRedirectPolicy.redirects(
            focusOwnerPID: focusOwnerPID,
            frontmostPID: frontmostPID,
            scriberPID: ProcessInfo.processInfo.processIdentifier,
            focusExposesTextInput: containsTextInput(ancestry(of: focused))
        ) else { return nil }
        return focusOwnerPID
    }

    /// The focused element's bounded ancestry, but only when that focus actually
    /// looks like text input.
    ///
    /// When macOS positively reports a focused element that is *not* text — a web
    /// page with no focused text box — record no Accessibility evidence at all. A
    /// live page mutates its own state between the before and after snapshots
    /// through carets, timers, and streaming content, and reading that drift as a
    /// paste mutation confirms insertions that never happened.
    ///
    /// An empty result is not a failure. Delivery still dispatches Paste, and
    /// confirmation falls to the pasteboard probe alone, which is the documented
    /// path for destinations that hide their editor from Accessibility.
    private func focusedTextAncestry(in application: AXUIElement, pid: pid_t) -> [AXUIElement] {
        if let focused = elementAttribute(application, named: kAXFocusedUIElementAttribute) {
            let ancestry = ancestry(of: focused)
            if containsTextInput(ancestry) { return ancestry }
        }
        let systemWide = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(systemWide, Self.accessibilityMessagingTimeout)
        guard let focused = elementAttribute(systemWide, named: kAXFocusedUIElementAttribute) else { return [] }
        var focusedPID: pid_t = 0
        guard AXUIElementGetPid(focused, &focusedPID) == .success, focusedPID == pid else { return [] }
        let ancestry = ancestry(of: focused)
        return containsTextInput(ancestry) ? ancestry : []
    }

    private func containsTextInput(_ ancestry: [AXUIElement]) -> Bool {
        ancestry.contains { isEditableTextElement($0) || isSecureTextElement($0) }
    }

    /// The focused element plus a bounded ancestor chain. Web-backed apps expose
    /// the real editor as an editable ancestor rather than the focused node, so
    /// both editable-ancestor attributes are consulted directly.
    private func ancestry(of focused: AXUIElement) -> [AXUIElement] {
        var ancestry = [focused]
        var current = focused
        for _ in 0..<Self.maximumInspectedAncestors {
            guard let parent = elementAttribute(current, named: kAXParentAttribute),
                  !ancestry.contains(where: { CFEqual($0, parent) }) else { break }
            ancestry.append(parent)
            current = parent
        }

        for attribute in ["AXEditableAncestor", "AXHighestEditableAncestor"] {
            if let editableAncestor = elementAttribute(focused, named: attribute),
               !ancestry.contains(where: { CFEqual($0, editableAncestor) }) {
                ancestry.insert(editableAncestor, at: 1)
            }
        }
        return ancestry
    }

    private func isSecureTextElement(_ element: AXUIElement) -> Bool {
        stringAttribute(element, named: kAXRoleAttribute) == "AXSecureTextField"
            || stringAttribute(element, named: kAXSubroleAttribute) == "AXSecureTextField"
    }

    private func isEditableTextElement(_ element: AXUIElement) -> Bool {
        let role = stringAttribute(element, named: kAXRoleAttribute)
        let subrole = stringAttribute(element, named: kAXSubroleAttribute)
        var selectedTextSettable = DarwinBoolean(false)
        let selectedTextStatus = AXUIElementIsAttributeSettable(
            element,
            kAXSelectedTextAttribute as CFString,
            &selectedTextSettable
        )
        var characterCountValue: CFTypeRef?
        let characterCountStatus = AXUIElementCopyAttributeValue(
            element,
            kAXNumberOfCharactersAttribute as CFString,
            &characterCountValue
        )
        var enabledValue: CFTypeRef?
        let enabledStatus = AXUIElementCopyAttributeValue(
            element,
            kAXEnabledAttribute as CFString,
            &enabledValue
        )
        let explicitlyEditable = boolAttribute(element, named: "AXIsEditable") == true
        return TextInputTargetPolicy.accepts(
            role: role,
            subrole: subrole,
            selectedTextSettable: selectedTextStatus == .success && selectedTextSettable.boolValue,
            exposesCharacterCount: characterCountStatus == .success && characterCountValue != nil,
            explicitlyEditable: explicitlyEditable,
            enabled: enabledStatus == .success ? enabledValue as? Bool : nil
        )
    }

    // MARK: - Delivery

    private func pasteAtCurrentSelection(_ text: String, into currentTarget: FocusedTextTarget) async -> PasteResult {
        // Re-resolve rather than comparing against the frontmost app: when focus
        // sits in a nonactivating panel the target is deliberately not frontmost.
        guard currentTargetPID() == currentTarget.pid else {
            return .failed("The focused app changed before Scriber could paste.")
        }

        let statesBeforePaste = observableTextStates(of: currentTarget.observationElements)
        let pasteboard = NSPasteboard.general
        let snapshot = PasteboardSnapshot.capture(pasteboard)
        pasteboard.clearContents()
        let pasteboardReadProbe = PasteboardReadProbe(text: text)
        let transcriptItem = NSPasteboardItem()
        guard transcriptItem.setDataProvider(pasteboardReadProbe, forTypes: [.string]) else {
            snapshot.restore(pasteboard)
            return .failed("The transcription could not be prepared for pasting.")
        }
        guard Self.transientPasteboardTypes.allSatisfy({
            transcriptItem.setString("", forType: $0)
        }), pasteboard.writeObjects([transcriptItem]) else {
            snapshot.restore(pasteboard)
            return .failed("The transcription could not be placed on the clipboard.")
        }
        let transcriptChangeCount = pasteboard.changeCount
        try? await Task.sleep(for: .milliseconds(75))
        guard await dispatchPaste(to: currentTarget) else {
            snapshot.restoreIfUnchanged(pasteboard, expectedChangeCount: transcriptChangeCount)
            return .failed("The focused app did not provide a usable Paste command.")
        }
        await waitForPasteboardRequest(pasteboardReadProbe)
        let stateAfterPaste = currentFocusedPasteTarget()
        let statesAfterPaste = stateAfterPaste?.pid == currentTarget.pid
            ? observableTextStates(of: stateAfterPaste?.observationElements ?? [])
            : []
        let pasteboardDataRequested = pasteboardReadProbe.wasRequested
        let accessibilityConfirmed = PasteConfirmationPolicy.qualifiesAsAccessibilityEvidence(
            focusContainsTextInput: currentTarget.focusContainsTextInput
                || (stateAfterPaste?.focusContainsTextInput ?? false),
            mutationObserved: (!statesBeforePaste.isEmpty || !statesAfterPaste.isEmpty)
                && statesBeforePaste != statesAfterPaste
        )
        guard PasteConfirmationPolicy.confirmsInsertion(
            accessibilityMutationObserved: accessibilityConfirmed,
            pasteboardDataRequested: pasteboardDataRequested
        ) else {
            return .noEditableTarget("No text box was focused to paste into")
        }
        scheduleClipboardRestore(
            snapshot,
            expectedChangeCount: transcriptChangeCount
        )
        return .inserted
    }

    private func waitForPasteboardRequest(_ probe: PasteboardReadProbe) async {
        let clock = ContinuousClock()
        let deadline = clock.now.advanced(by: Self.pasteRequestTimeout)
        while !probe.wasRequested, clock.now < deadline {
            try? await Task.sleep(for: .milliseconds(25))
        }
    }

    private func scheduleClipboardRestore(
        _ snapshot: PasteboardSnapshot,
        expectedChangeCount: Int
    ) {
        Task { @MainActor in
            try? await Task.sleep(for: Self.clipboardRestoreDelay)
            snapshot.restoreIfUnchanged(
                NSPasteboard.general,
                expectedChangeCount: expectedChangeCount
            )
        }
    }

    private func dispatchPaste(to target: FocusedTextTarget) async -> Bool {
        if performApplicationPasteCommand(in: target.application) {
            return true
        }
        return await postPasteShortcut(to: target.pid)
    }

    private func performApplicationPasteCommand(in application: AXUIElement) -> Bool {
        guard let menuBar = elementAttribute(application, named: kAXMenuBarAttribute),
              let pasteItem = pasteMenuItem(in: menuBar) else { return false }
        return AXUIElementPerformAction(pasteItem, kAXPressAction as CFString) == .success
    }

    private func pasteMenuItem(in root: AXUIElement) -> AXUIElement? {
        var queue = [root]
        var index = 0
        while index < queue.count, index < Self.maximumInspectedMenuItems {
            let element = queue[index]
            index += 1
            if stringAttribute(element, named: kAXRoleAttribute) == "AXMenuItem",
               boolAttribute(element, named: kAXEnabledAttribute) != false,
               isStandardPasteMenuItem(element) {
                return element
            }
            let remainingCapacity = Self.maximumInspectedMenuItems - queue.count
            if remainingCapacity > 0 {
                queue.append(
                    contentsOf: elementArrayAttribute(element, named: kAXChildrenAttribute)
                        .prefix(remainingCapacity)
                )
            }
        }
        return nil
    }

    private func isStandardPasteMenuItem(_ element: AXUIElement) -> Bool {
        let title = stringAttribute(element, named: kAXTitleAttribute)?.localizedLowercase
        if title == "paste" { return true }
        let commandCharacter = stringAttribute(element, named: "AXMenuItemCmdChar")?.lowercased()
        let commandModifiers = numberAttribute(element, named: "AXMenuItemCmdModifiers")?.intValue
        return commandCharacter == "v" && commandModifiers == 0
    }

    private func postPasteShortcut(to pid: pid_t) async -> Bool {
        guard let source = CGEventSource(stateID: .combinedSessionState),
              let down = CGEvent(keyboardEventSource: source, virtualKey: 9, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: 9, keyDown: false) else { return false }
        down.flags = .maskCommand
        up.flags = .maskCommand
        down.postToPid(pid)
        try? await Task.sleep(for: .milliseconds(12))
        up.postToPid(pid)
        return true
    }

    // MARK: - Accessibility attribute readers

    private func elementAttribute(_ element: AXUIElement, named name: String) -> AXUIElement? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, name as CFString, &value) == .success,
              let value,
              CFGetTypeID(value) == AXUIElementGetTypeID() else { return nil }
        return unsafeDowncast(value, to: AXUIElement.self)
    }

    private func stringAttribute(_ element: AXUIElement, named name: String) -> String? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, name as CFString, &value) == .success else { return nil }
        return value as? String
    }

    private func boolAttribute(_ element: AXUIElement, named name: String) -> Bool? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, name as CFString, &value) == .success else { return nil }
        return value as? Bool
    }

    private func numberAttribute(_ element: AXUIElement, named name: String) -> NSNumber? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, name as CFString, &value) == .success else { return nil }
        return value as? NSNumber
    }

    private func elementArrayAttribute(_ element: AXUIElement, named name: String) -> [AXUIElement] {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, name as CFString, &value) == .success,
              let values = value as? [Any] else { return [] }
        return values.compactMap { value in
            let reference = value as CFTypeRef
            guard CFGetTypeID(reference) == AXUIElementGetTypeID() else { return nil }
            return unsafeDowncast(reference, to: AXUIElement.self)
        }
    }

    private func observableTextStates(of elements: [AXUIElement]) -> [TextElementState] {
        elements.map { self.textState(of: $0) }.filter(\.hasObservableValue)
    }

    private func textState(of element: AXUIElement) -> TextElementState {
        var valueReference: CFTypeRef?
        let valueStatus = AXUIElementCopyAttributeValue(
            element,
            kAXValueAttribute as CFString,
            &valueReference
        )
        let value = valueStatus == .success ? valueReference as? String : nil

        var rangeReference: CFTypeRef?
        var selectedRange: NSRange?
        if AXUIElementCopyAttributeValue(
            element,
            kAXSelectedTextRangeAttribute as CFString,
            &rangeReference
        ) == .success,
           let rangeReference,
           CFGetTypeID(rangeReference) == AXValueGetTypeID() {
            let rangeValue = unsafeDowncast(rangeReference, to: AXValue.self)
            var range = CFRange()
            if AXValueGetValue(rangeValue, .cfRange, &range) {
                selectedRange = NSRange(location: range.location, length: range.length)
            }
        }

        var characterCountReference: CFTypeRef?
        let characterCount: Int?
        if AXUIElementCopyAttributeValue(
            element,
            kAXNumberOfCharactersAttribute as CFString,
            &characterCountReference
        ) == .success,
           let number = characterCountReference as? NSNumber {
            characterCount = number.intValue
        } else {
            characterCount = nil
        }
        return TextElementState(value: value, selectedRange: selectedRange, characterCount: characterCount)
    }

    // MARK: - Screen placement

    /// Resolves the pill's screen from the window server rather than from
    /// Accessibility. `CGWindowListCopyWindowInfo` returns windows front to back
    /// and exposes bounds without Screen Recording access.
    private static func screenContainingFrontmostWindow(ownedBy pid: pid_t) -> NSScreen? {
        guard let windows = CGWindowListCopyWindowInfo(
            [.optionOnScreenOnly, .excludeDesktopElements],
            kCGNullWindowID
        ) as? [[String: Any]] else { return nil }

        for window in windows {
            guard window[kCGWindowOwnerPID as String] as? pid_t == pid,
                  window[kCGWindowLayer as String] as? Int == 0,
                  let bounds = window[kCGWindowBounds as String] as? NSDictionary,
                  let frame = CGRect(dictionaryRepresentation: bounds) else { continue }
            return screen(containingQuartzRect: frame)
        }
        return nil
    }

    private static func screen(containingQuartzRect rect: CGRect) -> NSScreen? {
        // Quartz measures from the top of the primary display downwards, while
        // AppKit measures from its bottom upwards.
        let primaryTop = NSScreen.screens.first?.frame.maxY ?? 0
        let center = CGPoint(
            x: rect.midX,
            y: primaryTop - rect.midY
        )
        return NSScreen.screens.first { $0.frame.contains(center) }
    }
}

private struct TextElementState: Equatable {
    let value: String?
    let selectedRange: NSRange?
    let characterCount: Int?

    var hasObservableValue: Bool { value != nil || selectedRange != nil || characterCount != nil }
}

private struct FocusedTextTarget {
    let application: AXUIElement
    let pid: pid_t
    let observationElements: [AXUIElement]
    /// False when macOS reported a focused element that is not text input, which
    /// disqualifies any state change observed on it from counting as evidence.
    let focusContainsTextInput: Bool
}

private final class PasteboardReadProbe: NSObject, NSPasteboardItemDataProvider, @unchecked Sendable {
    private let textData: Data
    private let lock = NSLock()
    private var requested = false

    init(text: String) {
        textData = Data(text.utf8)
    }

    var wasRequested: Bool {
        lock.withLock { requested }
    }

    func pasteboard(
        _ pasteboard: NSPasteboard?,
        item: NSPasteboardItem,
        provideDataForType type: NSPasteboard.PasteboardType
    ) {
        if item.setData(textData, forType: type) {
            lock.withLock { requested = true }
        }
    }

    func pasteboardFinishedWithDataProvider(_ pasteboard: NSPasteboard) {}
}

private struct PasteboardSnapshot {
    let items: [[NSPasteboard.PasteboardType: Data]]

    static func capture(_ pasteboard: NSPasteboard) -> PasteboardSnapshot {
        let items = (pasteboard.pasteboardItems ?? []).map { item in
            Dictionary(uniqueKeysWithValues: item.types.compactMap { type in
                item.data(forType: type).map { (type, $0) }
            })
        }
        return PasteboardSnapshot(items: items)
    }

    /// Used when Scriber has already cleared the pasteboard but never published
    /// a transcript, so the user's own clipboard would otherwise be lost.
    func restore(_ pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        write(to: pasteboard)
    }

    func restoreIfUnchanged(_ pasteboard: NSPasteboard, expectedChangeCount: Int) {
        guard pasteboard.changeCount == expectedChangeCount else { return }
        pasteboard.clearContents()
        write(to: pasteboard)
    }

    private func write(to pasteboard: NSPasteboard) {
        let restored = items.map { values -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in values { item.setData(data, forType: type) }
            return item
        }
        if !restored.isEmpty { pasteboard.writeObjects(restored) }
    }
}
