@preconcurrency import AppKit
import ApplicationServices
import CoreGraphics
import Foundation
import os
#if SWIFT_PACKAGE
import ScriberCore
#endif

enum PasteResult: Sendable {
    static let noEditableTargetMessage = "No editable text box was focused"

    case inserted
    /// A password box had the cursor. Scriber refuses to type a dictation into
    /// one, and says so rather than falling through to a generic copied notice.
    case refusedSecureField
    case noEditableTarget(String)
    case failed(String)
}

/// Delivers a finished transcript to whatever text cursor is focused when
/// transcription completes.
///
/// Two rules shape this type:
///
/// 1. Starting a recording must stay instantaneous. Nothing on the record-start
///    path may send an Accessibility message, because those are synchronous
///    cross-process calls whose cost is set by the destination app, not by
///    Scriber. Target discovery therefore happens only at delivery time.
/// 2. Delivery is confirmed by one thing: the destination requesting the
///    concealed in-flight pasteboard item. The transcript is published only as a
///    promise, so nothing can insert what it never asked for. Nothing observed
///    after the paste is admitted as evidence — see `docs/PASTE_ENGINE.md`.
@MainActor
final class PasteService {
    /// Accessibility messages block the caller. macOS defaults to a 6-second
    /// per-message timeout, and an unresponsive destination can spend all of it
    /// while Scriber's main actor waits. Delivery never depends on Accessibility
    /// succeeding, so every message is capped low enough to stay imperceptible.
    private static let accessibilityMessagingTimeout: Float = 0.2
    private static let maximumInspectedAncestors = 8
    /// How long a destination has to ask for the transcript before delivery is
    /// called a failure. Nothing else is waited on, so this is the entire cost of
    /// a dictation that goes nowhere, and a delivery that lands pays only the
    /// time the destination actually took.
    private static let deliveryConfirmationBudget = Duration.milliseconds(1_000)
    /// How long the transcript stays on the clipboard after a destination has
    /// taken it, before the user's own clipboard goes back.
    ///
    /// Requesting the promised string is not the same as having finished pasting.
    /// A destination may read the pasteboard more than once — once to see what is
    /// on offer and again to insert — and restoring between those two reads hands
    /// it the clipboard the user had before, which it then pastes instead of the
    /// dictation. Google Docs does this in a table cell roughly one time in five.
    ///
    /// Nothing waits on this. The pill is already gone and the outcome is already
    /// decided, so the delay costs the user nothing and only has to outlast a
    /// destination finishing its own paste.
    private static let clipboardRestoreDelay = Duration.milliseconds(500)
    private static let transientPasteboardTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]

    private(set) var targetScreen: NSScreen?

    /// Records only where the floating pill should appear. The frontmost window
    /// rectangle comes from the window server, so this performs no Accessibility
    /// traversal and adds no measurable latency to starting a recording.
    @discardableResult
    func captureTarget() -> NSScreen? {
        targetScreen = nil
        guard let runningApplication = NSWorkspace.shared.frontmostApplication else { return nil }
        targetScreen = Self.screenContainingFrontmostWindow(ownedBy: runningApplication.processIdentifier)
        return targetScreen
    }

    func clearTarget() {
        targetScreen = nil
    }

    /// A dictation that lands leaves the clipboard exactly as it found it. The
    /// transcript travels as a concealed, promised item, so clipboard managers
    /// cannot take a copy of dictation in flight nor fake the request that
    /// confirms delivery, and once the destination has taken it the user's own
    /// clipboard comes back.
    ///
    /// A dictation that does not land stays on the clipboard as ordinary text,
    /// because that is the only place the user can recover it from without
    /// opening a window.
    /// - Parameter onDispatched: Called the moment the Paste has been sent, before
    ///   anything is known about whether it landed. Learning that takes up to a
    ///   second more, and making the user watch a spinner through it is what made
    ///   delivery feel slow while its total time was unchanged.
    func insert(
        _ text: String,
        onDispatched: @MainActor () -> Void = {}
    ) async -> PasteResult {
        guard AXIsProcessTrusted() else { return .failed("Accessibility permission is not enabled.") }
        let resolution = resolveTarget()
        logDeliveryContext(chosen: resolution.target)
        switch resolution {
        case .secureField:
            logDeliveryOutcome("refusedSecureField")
            return .refusedSecureField
        case .none:
            logDeliveryOutcome("noEditableTarget-noTarget")
            return .noEditableTarget(PasteResult.noEditableTargetMessage)
        case .target(let target):
            let result = await pasteAtCurrentSelection(text, into: target, onDispatched: onDispatched)
            switch result {
            case .inserted: logDeliveryOutcome("inserted")
            case .refusedSecureField: logDeliveryOutcome("refusedSecureField")
            case .noEditableTarget: logDeliveryOutcome("noEditableTarget")
            case .failed: logDeliveryOutcome("failed")
            }
            return result
        }
    }

    // MARK: - Delivery diagnostics
    //
    // Privacy-safe diagnostics for target selection. Scriber picks its paste target
    // with `NSWorkspace.frontmostApplication`, but an LSUIElement app presenting a
    // nonactivating panel can hold keyboard focus without becoming frontmost.
    //
    // Record process identities and Accessibility roles only. Never log transcript
    // text: keeping in-flight dictation private is the whole point of the
    // concealed-pasteboard design, and a log would undo it.

    private static let diagnosticLog = Logger(
        subsystem: "com.gafiegarcia.scriber",
        category: "paste-target"
    )

    private func logDeliveryContext(chosen: FocusedTextTarget?) {
        let frontmost = NSWorkspace.shared.frontmostApplication?.processIdentifier
        let systemWide = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(systemWide, Self.accessibilityMessagingTimeout)

        var focusedApplicationPID: pid_t = 0
        if let focusedApplication = elementAttribute(systemWide, named: kAXFocusedApplicationAttribute) {
            AXUIElementGetPid(focusedApplication, &focusedApplicationPID)
        }

        var focusedElementPID: pid_t = 0
        var role = "-"
        var subrole = "-"
        if let focusedElement = elementAttribute(systemWide, named: kAXFocusedUIElementAttribute) {
            AXUIElementGetPid(focusedElement, &focusedElementPID)
            role = stringAttribute(focusedElement, named: kAXRoleAttribute) ?? "-"
            subrole = stringAttribute(focusedElement, named: kAXSubroleAttribute) ?? "-"
        }

        Self.diagnosticLog.notice("""
        delivery frontmost=\(Self.identity(of: frontmost), privacy: .public) \
        focusedApp=\(Self.identity(of: focusedApplicationPID), privacy: .public) \
        focusedElement=\(Self.identity(of: focusedElementPID), privacy: .public) \
        role=\(role, privacy: .public) subrole=\(subrole, privacy: .public) \
        chosen=\(Self.identity(of: chosen?.pid), privacy: .public)
        """)
    }

    private func logDeliveryOutcome(_ outcome: String) {
        Self.diagnosticLog.notice("delivery outcome=\(outcome, privacy: .public)")
    }

    /// The inputs to the confirmation decision, so a delivery that was reported
    /// wrongly can be read back rather than reasoned about. Counts only — never
    /// the transcript, and never a field's contents.
    ///
    /// `asked` is the whole decision. `elapsedMs` is what it cost.
    private func logDeliveryEvidence(askedCount: Int, elapsedMilliseconds: Int) {
        Self.diagnosticLog.notice("""
        delivery evidence asked=\(askedCount, privacy: .public) \
        elapsedMs=\(elapsedMilliseconds, privacy: .public)
        """)
    }

    private static func identity(of pid: pid_t?) -> String {
        guard let pid, pid != 0 else { return "none" }
        let application = NSRunningApplication(processIdentifier: pid)
        return "\(application?.bundleIdentifier ?? "unknown")(\(pid))"
    }

    // MARK: - Target discovery

    /// The process delivery should paste into, and nothing else.
    ///
    /// What is focused is read for exactly one purpose: refusing a password box.
    /// It is deliberately not consulted for anything else. Focus says where a
    /// paste would land, never that one did, and a real search field held the
    /// cursor through three deliveries that inserted nothing.
    private func resolveTarget() -> TargetResolution {
        guard let pid = currentTargetPID() else { return .none }
        guard !focusedAncestry(in: pid).contains(where: isSecureTextElement) else { return .secureField }
        return .target(FocusedTextTarget(pid: pid))
    }

    /// The process delivery should paste into.
    ///
    /// Normally the frontmost application, but keyboard focus wins when the two
    /// disagree. An accessory app presenting a nonactivating panel — Raycast's
    /// command bar, and Scriber's own pill — holds focus without ever becoming
    /// frontmost, and delivery must follow the caret the user can actually see.
    private func currentTargetPID() -> pid_t? {
        guard let frontmostPID = NSWorkspace.shared.frontmostApplication?.processIdentifier else { return nil }
        return keyboardFocusOwner(frontmostPID: frontmostPID) ?? frontmostPID
    }

    private func keyboardFocusOwner(frontmostPID: pid_t) -> pid_t? {
        let systemWide = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(systemWide, Self.accessibilityMessagingTimeout)
        guard let focused = elementAttribute(systemWide, named: kAXFocusedUIElementAttribute) else { return nil }
        var focusOwnerPID: pid_t = 0
        guard AXUIElementGetPid(focused, &focusOwnerPID) == .success else { return nil }
        guard KeyboardFocusRedirectPolicy.redirects(
            focusOwnerPID: focusOwnerPID,
            frontmostPID: frontmostPID,
            scriberPID: ProcessInfo.processInfo.processIdentifier,
            focusExposesTextInput: containsTextInput(ancestry(of: focused))
        ) else { return nil }
        return focusOwnerPID
    }

    /// The focused element's bounded ancestry within one process, asked of the
    /// application first and the system-wide element second.
    ///
    /// An empty result is not a failure and never refuses a paste. Zed and VS Code
    /// keep their real editor out of the Accessibility tree entirely and still
    /// accept an ordinary Command-V.
    private func focusedAncestry(in pid: pid_t) -> [AXUIElement] {
        let application = AXUIElementCreateApplication(pid)
        AXUIElementSetMessagingTimeout(application, Self.accessibilityMessagingTimeout)
        if let focused = elementAttribute(application, named: kAXFocusedUIElementAttribute) {
            return ancestry(of: deepestFocus(from: focused))
        }
        let systemWide = AXUIElementCreateSystemWide()
        AXUIElementSetMessagingTimeout(systemWide, Self.accessibilityMessagingTimeout)
        guard let focused = elementAttribute(systemWide, named: kAXFocusedUIElementAttribute) else { return [] }
        var focusedPID: pid_t = 0
        guard AXUIElementGetPid(focused, &focusedPID) == .success, focusedPID == pid else { return [] }
        return ancestry(of: deepestFocus(from: focused))
    }

    /// Follows focus downwards to the element that actually holds the caret.
    ///
    /// An application can answer `AXFocusedUIElement` with a container that
    /// answers the same question again — Zen names the page's `AXWebArea`, which
    /// names the editor inside it. `ancestry(of:)` only ever walks upwards, so
    /// stopping at the container would hide a secure field sitting underneath it.
    private func deepestFocus(from element: AXUIElement) -> AXUIElement {
        var current = element
        for _ in 0..<Self.maximumInspectedAncestors {
            guard let next = elementAttribute(current, named: kAXFocusedUIElementAttribute),
                  !CFEqual(next, current) else { break }
            current = next
        }
        return current
    }

    private func containsTextInput(_ ancestry: [AXUIElement]) -> Bool {
        ancestry.contains { isEditableTextElement($0) || isSecureTextElement($0) }
    }

    /// The focused element plus a bounded ancestor chain. Web-backed apps expose
    /// the real editor as an editable ancestor rather than the focused node, so
    /// both editable-ancestor attributes are consulted directly.
    private func ancestry(of focused: AXUIElement) -> [AXUIElement] {
        var ancestry = [focused]
        var current = focused
        for _ in 0..<Self.maximumInspectedAncestors {
            guard let parent = elementAttribute(current, named: kAXParentAttribute),
                  !ancestry.contains(where: { CFEqual($0, parent) }) else { break }
            ancestry.append(parent)
            current = parent
        }

        for attribute in ["AXEditableAncestor", "AXHighestEditableAncestor"] {
            if let editableAncestor = elementAttribute(focused, named: attribute),
               !ancestry.contains(where: { CFEqual($0, editableAncestor) }) {
                ancestry.insert(editableAncestor, at: 1)
            }
        }
        return ancestry
    }

    private func isSecureTextElement(_ element: AXUIElement) -> Bool {
        stringAttribute(element, named: kAXRoleAttribute) == "AXSecureTextField"
            || stringAttribute(element, named: kAXSubroleAttribute) == "AXSecureTextField"
    }

    private func isEditableTextElement(_ element: AXUIElement) -> Bool {
        let role = stringAttribute(element, named: kAXRoleAttribute)
        let subrole = stringAttribute(element, named: kAXSubroleAttribute)
        var selectedTextSettable = DarwinBoolean(false)
        let selectedTextStatus = AXUIElementIsAttributeSettable(
            element,
            kAXSelectedTextAttribute as CFString,
            &selectedTextSettable
        )
        var characterCountValue: CFTypeRef?
        let characterCountStatus = AXUIElementCopyAttributeValue(
            element,
            kAXNumberOfCharactersAttribute as CFString,
            &characterCountValue
        )
        var enabledValue: CFTypeRef?
        let enabledStatus = AXUIElementCopyAttributeValue(
            element,
            kAXEnabledAttribute as CFString,
            &enabledValue
        )
        let explicitlyEditable = boolAttribute(element, named: "AXIsEditable") == true
        return TextInputTargetPolicy.accepts(
            role: role,
            subrole: subrole,
            selectedTextSettable: selectedTextStatus == .success && selectedTextSettable.boolValue,
            exposesCharacterCount: characterCountStatus == .success && characterCountValue != nil,
            explicitlyEditable: explicitlyEditable,
            enabled: enabledStatus == .success ? enabledValue as? Bool : nil
        )
    }

    // MARK: - Delivery

    private func pasteAtCurrentSelection(
        _ text: String,
        into currentTarget: FocusedTextTarget,
        onDispatched: @MainActor () -> Void
    ) async -> PasteResult {
        // Re-resolve rather than comparing against the frontmost app: when focus
        // sits in a nonactivating panel the target is deliberately not frontmost.
        guard currentTargetPID() == currentTarget.pid else {
            return .failed("The focused app changed before Scriber could paste.")
        }

        let pasteboard = NSPasteboard.general
        let snapshot = PasteboardSnapshot.capture(pasteboard)
        pasteboard.clearContents()
        let pasteboardReadProbe = PasteboardReadProbe(text: text)
        let transcriptItem = NSPasteboardItem()
        guard transcriptItem.setDataProvider(pasteboardReadProbe, forTypes: [.string]) else {
            snapshot.restore(pasteboard)
            return .failed("The transcription could not be prepared for pasting.")
        }
        guard Self.transientPasteboardTypes.allSatisfy({
            transcriptItem.setString("", forType: $0)
        }), pasteboard.writeObjects([transcriptItem]) else {
            snapshot.restore(pasteboard)
            return .failed("The transcription could not be placed on the clipboard.")
        }
        // No settle before the keystroke. `writeObjects` is synchronous and every
        // write above is checked, so the pasteboard already holds the transcript
        // when this line is reached; the Command-V cannot outrun it. A 75 ms sleep
        // sat here, added by the same undocumented commit as the Paste menu item,
        // waiting on a step AppKit does not have.
        let transcriptChangeCount = pasteboard.changeCount
        let deliveryStarted = ContinuousClock().now
        guard await postPasteShortcut(to: currentTarget.pid) else {
            snapshot.restoreIfUnchanged(pasteboard, expectedChangeCount: transcriptChangeCount)
            return .failed("Scriber could not send a Paste command.")
        }
        onDispatched()
        let requested = await waitForTranscriptToBeTaken(
            pasteboardReadProbe,
            until: deliveryStarted.advanced(by: Self.deliveryConfirmationBudget)
        )
        logDeliveryEvidence(
            askedCount: pasteboardReadProbe.requestCount,
            elapsedMilliseconds: deliveryStarted.duration(to: ContinuousClock().now).milliseconds
        )
        guard PasteConfirmationPolicy.confirmsInsertion(pasteboardDataRequested: requested) else {
            // Nothing asked for the promised transcript, so nothing inserted it.
            // Leave it behind as ordinary text: the recovery pill points at the
            // clipboard, and that is the only place the user reaches without
            // opening a window.
            publishTranscriptAsOrdinaryText(text, expectedChangeCount: transcriptChangeCount)
            return .noEditableTarget("No text box was focused to paste into")
        }
        // The destination has the transcript, so the user's own clipboard can come
        // back. A dictation that lands leaves no trace on it, the way pressing
        // Command-V yourself would not — but not yet, and not on this path.
        scheduleClipboardRestore(snapshot, expectedChangeCount: transcriptChangeCount)
        return .inserted
    }

    /// Waits for the destination to ask for the promised transcript.
    ///
    /// This is the only thing delivery ever waits on, and the only thing that can
    /// confirm it. The transcript is published as a promise, so it does not exist
    /// until something asks; a destination that never asked cannot have inserted
    /// it, and one that asked was pasting.
    ///
    /// The one destination that ever seemed to break this — Raycast Notes on a
    /// note that had just been opened, asking and inserting nothing — was asking
    /// honestly. Its paste was handed the user's previous clipboard, because the
    /// restore ran before it had finished reading. See `clipboardRestoreDelay`.
    private func waitForTranscriptToBeTaken(
        _ probe: PasteboardReadProbe,
        until deadline: ContinuousClock.Instant
    ) async -> Bool {
        let clock = ContinuousClock()
        while clock.now < deadline {
            if probe.wasRequested { return true }
            try? await Task.sleep(for: .milliseconds(10))
        }
        return probe.wasRequested
    }

    /// Puts the user's clipboard back once the destination has had time to finish
    /// pasting, rather than the moment it asked.
    ///
    /// `restoreIfUnchanged` is what makes the delay safe: anything writing to the
    /// clipboard in the meantime — the user copying something, or the next
    /// dictation — moves the change count, and the restore is abandoned rather
    /// than overwriting it.
    private func scheduleClipboardRestore(_ snapshot: PasteboardSnapshot, expectedChangeCount: Int) {
        Task { @MainActor in
            try? await Task.sleep(for: Self.clipboardRestoreDelay)
            snapshot.restoreIfUnchanged(
                NSPasteboard.general,
                expectedChangeCount: expectedChangeCount
            )
        }
    }

    /// Replaces the concealed in-flight item with a plain one, so a transcript
    /// that could not be delivered behaves as though the user had copied it
    /// themselves — a clipboard manager keeps it, and pasting it works.
    private func publishTranscriptAsOrdinaryText(_ text: String, expectedChangeCount: Int) {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount == expectedChangeCount else { return }
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    /// Command-V, and only Command-V.
    ///
    /// The event source is private rather than the combined session state, which
    /// reflects the keys physically down right now. A modifier still held when
    /// delivery fires — a hands-free dictation whose chord has not been released,
    /// or a launcher hotkey — merges into a session-state event and turns this
    /// into Shift-Command-V or Option-Command-V, which paste differently or not
    /// at all. A private source carries only the flags set here.
    ///
    /// This is the only way Scriber asks a destination to paste. Two alternatives
    /// were tried and must not come back. Pressing the destination's own Edit menu
    /// item through Accessibility takes keyboard focus off the field being pasted
    /// into, so the Paste it then performs has nowhere to go. Posting the event at
    /// the HID level rather than into the target process (82b1bdd) fixed nothing
    /// and made Google Docs paste the previous clipboard item.
    private func postPasteShortcut(to pid: pid_t) async -> Bool {
        guard let source = CGEventSource(stateID: .privateState),
              let down = CGEvent(keyboardEventSource: source, virtualKey: 9, keyDown: true),
              let up = CGEvent(keyboardEventSource: source, virtualKey: 9, keyDown: false) else { return false }
        down.flags = .maskCommand
        up.flags = .maskCommand
        down.postToPid(pid)
        try? await Task.sleep(for: .milliseconds(12))
        up.postToPid(pid)
        return true
    }

    // MARK: - Accessibility attribute readers

    private func elementAttribute(_ element: AXUIElement, named name: String) -> AXUIElement? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, name as CFString, &value) == .success,
              let value,
              CFGetTypeID(value) == AXUIElementGetTypeID() else { return nil }
        return unsafeDowncast(value, to: AXUIElement.self)
    }

    private func stringAttribute(_ element: AXUIElement, named name: String) -> String? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, name as CFString, &value) == .success else { return nil }
        return value as? String
    }

    private func boolAttribute(_ element: AXUIElement, named name: String) -> Bool? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, name as CFString, &value) == .success else { return nil }
        return value as? Bool
    }

    // MARK: - Screen placement

    /// Resolves the pill's screen from the window server rather than from
    /// Accessibility. `CGWindowListCopyWindowInfo` returns windows front to back
    /// and exposes bounds without Screen Recording access.
    private static func screenContainingFrontmostWindow(ownedBy pid: pid_t) -> NSScreen? {
        guard let windows = CGWindowListCopyWindowInfo(
            [.optionOnScreenOnly, .excludeDesktopElements],
            kCGNullWindowID
        ) as? [[String: Any]] else { return nil }

        for window in windows {
            guard window[kCGWindowOwnerPID as String] as? pid_t == pid,
                  window[kCGWindowLayer as String] as? Int == 0,
                  let bounds = window[kCGWindowBounds as String] as? NSDictionary,
                  let frame = CGRect(dictionaryRepresentation: bounds) else { continue }
            return screen(containingQuartzRect: frame)
        }
        return nil
    }

    private static func screen(containingQuartzRect rect: CGRect) -> NSScreen? {
        // Quartz measures from the top of the primary display downwards, while
        // AppKit measures from its bottom upwards.
        let primaryTop = NSScreen.screens.first?.frame.maxY ?? 0
        let center = CGPoint(
            x: rect.midX,
            y: primaryTop - rect.midY
        )
        return NSScreen.screens.first { $0.frame.contains(center) }
    }
}

private extension Duration {
    var milliseconds: Int {
        Int(components.seconds * 1_000 + components.attoseconds / 1_000_000_000_000_000)
    }
}

/// The process a delivery is aimed at. Only the pid: everything else this once
/// carried described what was focused, and none of it could confirm a paste.
private struct FocusedTextTarget {
    let pid: pid_t
}

/// What target discovery found. A password box is kept distinct from finding
/// nothing, because the two call for opposite things to be said to the user.
private enum TargetResolution {
    case target(FocusedTextTarget)
    case secureField
    case none

    var target: FocusedTextTarget? {
        if case .target(let target) = self { return target }
        return nil
    }
}

private final class PasteboardReadProbe: NSObject, NSPasteboardItemDataProvider, @unchecked Sendable {
    private let textData: Data
    private let lock = NSLock()
    private var requested = false
    private var calls = 0

    init(text: String) {
        textData = Data(text.utf8)
    }

    var wasRequested: Bool {
        lock.withLock { requested }
    }

    /// How many times a destination asked for the promised transcript, whether or
    /// not serving it succeeded. Separating this from `wasRequested` distinguishes
    /// "nobody asked" from "somebody asked and Scriber failed to answer" — the two
    /// look identical otherwise, and they call for opposite fixes.
    var requestCount: Int {
        lock.withLock { calls }
    }

    func pasteboard(
        _ pasteboard: NSPasteboard?,
        item: NSPasteboardItem,
        provideDataForType type: NSPasteboard.PasteboardType
    ) {
        lock.withLock { calls += 1 }
        if item.setData(textData, forType: type) {
            lock.withLock { requested = true }
        }
    }

    func pasteboardFinishedWithDataProvider(_ pasteboard: NSPasteboard) {}
}

private struct PasteboardSnapshot {
    let items: [[NSPasteboard.PasteboardType: Data]]

    static func capture(_ pasteboard: NSPasteboard) -> PasteboardSnapshot {
        let items = (pasteboard.pasteboardItems ?? []).map { item in
            Dictionary(uniqueKeysWithValues: item.types.compactMap { type in
                item.data(forType: type).map { (type, $0) }
            })
        }
        return PasteboardSnapshot(items: items)
    }

    /// Used when Scriber has already cleared the pasteboard but never published
    /// a transcript, so the user's own clipboard would otherwise be lost.
    func restore(_ pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        write(to: pasteboard)
    }

    func restoreIfUnchanged(_ pasteboard: NSPasteboard, expectedChangeCount: Int) {
        guard pasteboard.changeCount == expectedChangeCount else { return }
        pasteboard.clearContents()
        write(to: pasteboard)
    }

    private func write(to pasteboard: NSPasteboard) {
        let restored = items.map { values -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in values { item.setData(data, forType: type) }
            return item
        }
        if !restored.isEmpty { pasteboard.writeObjects(restored) }
    }
}
